version: '3.8'

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${PASSWORD}
      MYSQL_DATABASE: ${DATABASE}
      MYSQL_USER: ${USERNAME}
      MYSQL_PASSWORD: ${PASSWORD}
    ports:
      - "3307:3306"
    volumes:
      - mysql-data:/var/lib/mysql

  # web:
  #   build: ./
  #   command: sh -c "while !</dev/tcp/mysql/3306; do sleep 1; done; poetry run alembic upgrade head && poetry run uvicorn app.main:app --host 0.0.0.0 --port 8000"
  #   volumes:
  #     - ./app:/app
  #   ports:
  #     - "8000:8000"
  #   depends_on:
  #     - mysql
  #   env_file:
  #     - .env

volumes:
  mysql-data:
